### ISSUE TITLE
Unable to add uncombined file succesfully

### ISSUE THREAD

**Issue by pixeloution** [tonydewan/Carabiner#1]
According to the documentation the following format should work:

```
$this->carabiner->css('home.css', 'screen', 'home.css', FALSE );
```

I've also tried:

```
$this->carabiner->css('home.css', 'screen', '', FALSE );
```

The other files added, which are combined, work and output properly. This particular file is linked as being in the /cache/ directory but no such file exists.

**Comment by mark-the-spark** [comment]
I am also having this issue.  I'll see if I can figure out what is wrong, but I'm not normally too hot on these things.  

Is the author aware of the issue?

**Comment by tonydewan** [comment]
As I mention in the README, I'm no longer actively supporting this project. I'm happy to merge pull requests, but can't commit to active development.
