### ISSUE TITLE
Module assets

### ISSUE THREAD

**Issue by Exelord** [tonydewan/Carabiner#11]
Hi,
There is an option for load assets from module? for example:
the css path is `APPPATH.'modules'` and we can add modules asset path next like `test_module/assets/css/test.css`

**Comment by colonelclick** [comment]
Yes you can, but you need to set the base folder for carabiner to the
folder that contains all your modules. Then you can pass the module and
subpath in your controller, and it will look for that path in the base
folder defined in the carabiner.php config file.

To put it another way, Carabiner function calls handle not just filenames,
but relative paths preceding the filenames as well, relative from the
folder defined in carabiner.php.
