### ISSUE TITLE
Usage guidelines do not explain the minify parameter

### ISSUE THREAD

**Issue by jamieburchell** [tonydewan/Carabiner#4]
In the usage guidelines the optional boolean "minify" parameter is not explained and there are no examples of its usage.

**Comment by colonelclick** [comment]
Minify just means to remove extra characters like white space and formatting from a file.

http://en.wikipedia.org/wiki/Minification_(programming)

**Comment by jamieburchell** [comment]
Hi, yep I understand what minification is, but the documentation doesn't state which parameter of the method controls it. It looks like it was added last and not added to any documentation as even the comments above the method don't include the description for that parameter.

**Comment by colonelclick** [comment]
Ah yes, I see what you are saying now. Good catch. I will look at adding this to the docs. It is the 4th and 5th parameter of the JS and CSS functions, respectively.

```
-----------------------------------------------------------------------------------------------
    And to prevent an individual asset file from being minified:
    // JS: pass a boolean FALSE as the fourth attribute of the method
    // CSS: pass a boolean FALSE as the fifth attribute of the method
-----------------------------------------------------------------------------------------------
```

**Comment by jamieburchell** [comment]
Thanks :)
