### ISSUE TITLE
Combining Javascript files not ending by a semicolon

### ISSUE THREAD

**Issue by shaffe-fr** [tonydewan/Carabiner#5]
When we combine two javascript files that do not end with a semi-colon, a javascript error is raised.
 It can happen when libraries like jQuery are used.
 Here is a sample.
$(function(){ /// My code})
 When using that statement in a single file no error is raised, because the semi-colon (;) is not required, it's only strongly advised.
 If we combine another file to this sample an error can be raised.
 The fix is easy : 
 in libraries/carabiner.php at the line 964 and 970, replace 
$file_data .= $this->_minify( $flag, $file['dev'] ) . "\n";
 and 
$file_data .= $this->_get_contents( $r ) ."\n";
 by 
$file_data .= $this->_minify( $flag, $file['dev'] ) . ";\n";
 and 
$file_data .= $this->_get_contents( $r ) .";\n";

**Comment by tonydewan** [comment]
Interesting. Feel free to submit a pull request test and I'll merge it in. Thanks!
